[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/case-save"
  to   = "/.netlify/functions/case-save"
  status = 200

[[redirects]]
  from = "/case/*"
  to   = "/.netlify/functions/case-view"
  status = 200
